# Project information
site_name: 天津理工大学新生入学指南
site_description: 帮助天理新生快速适应学校以及避坑
site_url: http://BattiestStone4.github.io

# Navigation
nav:
  - 首页: index.md
  - 问答: questions.md
# Configuration
theme:
  name: material
  language: zh
  palette:
    primary: light blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant